version: '3.5' # We use version 3.5 syntax
services:
  mockServer:
    image: mockserver/mockserver:latest
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: config/initializerJson.json
    volumes:
      - ./config:/config
  # angular-ui:
  #   build:
  #     context: ./mindata-tech-test
  #   ports:
  #     - 4200:4200
  #   container_name: angular-ui
  #   volumes:
  #       - ./mindata-tech-test:/usr/src/app/app-ui
  #       - /usr/src/app/app-ui/node_modules
